import 'models/product.dart';

final List<Product> donutList = [
  Product(
    id: 'd1',
    name: 'Chocolate Donut',
    vendor: "Dunkin's",
    price: 36,
    imageUrl: 'assets/images/chocolate_donut.png',
    colorHex: 'FFC0CB',
    description: 'Delicious chocolate donut',
    ingredients: {'Sugar': '8g'},
  ),
  Product(
    id: 'd2',
    name: 'Grape Donut',
    vendor: "Dunkin's",
    price: 45,
    imageUrl: 'assets/images/grape_donut.png',
    colorHex: 'E0FFFF',
    description: 'Sweet grape glazed donut',
    ingredients: {'Sugar': '10g'},
  ),
  Product(
    id: 'd3',
    name: 'Ice Cream Donut',
    vendor: "Dunkin's",
    price: 45,
    imageUrl: 'assets/images/icecream_donut.png',
    colorHex: 'FFE4E1',
    description: 'Donut with vanilla ice cream',
    ingredients: {'Sugar': '12g'},
  ),
  Product(
    id: 'd4',
    name: 'Strawberry Donut',
    vendor: "Dunkin's",
    price: 84,
    imageUrl: 'assets/images/strawberry_donut.png',
    colorHex: 'FFF0F5',
    description: 'Classic strawberry glazed donut',
    ingredients: {'Sugar': '9g'},
  ),
];

final List<Product> burgerList = [
  Product(
    id: 'b1',
    name: 'BBQ Burger',
    vendor: "McDonald's",
    price: 65,
    imageUrl: 'assets/images/BBQ_burger.png',
    colorHex: 'FFE4B5',
    description: 'Juicy BBQ burger',
    ingredients: {'Beef': '150g', 'Sauce': 'BBQ'},
  ),
  Product(
    id: 'b2',
    name: 'Bacon Burger',
    vendor: "Burger King",
    price: 75,
    imageUrl: 'assets/images/bacon_burger.png',
    colorHex: 'FFDAB9',
    description: 'Bacon and cheese burger',
    ingredients: {'Beef': '150g', 'Bacon': '2 strips'},
  ),
  Product(
    id: 'b3',
    name: 'Beefy Burger',
    vendor: "Wendy's",
    price: 85,
    imageUrl: 'assets/images/beefy_burger.png',
    colorHex: 'F5DEB3',
    description: 'Double beef burger',
    ingredients: {'Beef': '300g'},
  ),
  Product(
    id: 'b4',
    name: 'Caramel Burger',
    vendor: "Local Diner",
    price: 95,
    imageUrl: 'assets/images/caramel_burger.png',
    colorHex: 'DEB887',
    description: 'A unique sweet and savory burger',
    ingredients: {'Beef': '150g', 'Caramel': '20g'},
  ),
];

final List<Product> smoothieList = [
  Product(
    id: 's1',
    name: 'Blueberry Smoothie',
    vendor: "Smoothie King",
    price: 40,
    imageUrl: 'assets/images/smoothie_blueberry.png',
    colorHex: 'E6E6FA',
    description: 'Fresh blueberry smoothie',
    ingredients: {'Blueberries': '1 cup'},
  ),
  Product(
    id: 's2',
    name: 'Green Smoothie',
    vendor: "Jamba Juice",
    price: 45,
    imageUrl: 'assets/images/smoothie_green.png',
    colorHex: 'F0FFF0',
    description: 'Healthy green smoothie',
    ingredients: {'Spinach': '1 cup', 'Apple': '1'},
  ),
  Product(
    id: 's3',
    name: 'Mango Smoothie',
    vendor: "Tropical Smoothie Cafe",
    price: 50,
    imageUrl: 'assets/images/smoothie_mango.png',
    colorHex: 'FFFACD',
    description: 'Tropical mango smoothie',
    ingredients: {'Mango': '1 cup'},
  ),
  Product(
    id: 's4',
    name: 'Strawberry Smoothie',
    vendor: "Smoothie King",
    price: 45,
    imageUrl: 'assets/images/smoothie_strawberry.png',
    colorHex: 'FFE4E1',
    description: 'Classic strawberry smoothie',
    ingredients: {'Strawberries': '1 cup'},
  ),
];

final List<Product> pancakeList = [
  Product(
    id: 'p1',
    name: 'Original Pancake',
    vendor: "IHOP",
    price: 30,
    imageUrl: 'assets/images/pancake.png',
    colorHex: 'FFF8DC',
    description: 'Original buttermilk pancakes',
    ingredients: {'Flour': '1 cup', 'Syrup': '2tbsp'},
  ),
  Product(
    id: 'p2',
    name: 'Banana Pancake',
    vendor: "Denny's",
    price: 35,
    imageUrl: 'assets/images/pancake_banana.png',
    colorHex: 'FFFFE0',
    description: 'Pancakes with fresh bananas',
    ingredients: {'Flour': '1 cup', 'Banana': '1'},
  ),
  Product(
    id: 'p3',
    name: 'Blueberry Pancake',
    vendor: "IHOP",
    price: 40,
    imageUrl: 'assets/images/pancake_blueberry.png',
    colorHex: 'E6E6FA',
    description: 'Pancakes loaded with blueberries',
    ingredients: {'Flour': '1 cup', 'Blueberries': '1/2 cup'},
  ),
  Product(
    id: 'p4',
    name: 'Chocolate Pancake',
    vendor: "IHOP",
    price: 45,
    imageUrl: 'assets/images/pancake_chocolate.png',
    colorHex: 'FFEBCD',
    description: 'Chocolate chip pancakes',
    ingredients: {'Flour': '1 cup', 'Chocolate Chips': '2tbsp'},
  ),
  Product(
    id: 'p5',
    name: 'Traditional Pancake',
    vendor: "Local Diner",
    price: 25,
    imageUrl: 'assets/images/pancake_tradicional.png',
    colorHex: 'FDF5E6',
    description: 'Traditional homemade pancakes',
    ingredients: {'Flour': '1 cup'},
  ),
];

final List<Product> pizzaList = [
  Product(
    id: 'pz1',
    name: '3 Cheese Pizza',
    vendor: "Pizza Hut",
    price: 80,
    imageUrl: 'assets/images/pizza_3quesos.png',
    colorHex: 'FFFACD',
    description: 'Mozzarella, cheddar, and parmesan',
    ingredients: {'Cheese': '3 kinds'},
  ),
  Product(
    id: 'pz2',
    name: 'Hawaiian Pizza',
    vendor: "Domino's",
    price: 90,
    imageUrl: 'assets/images/pizza_hawaiana.png',
    colorHex: 'FFE4B5',
    description: 'Ham and pineapple pizza',
    ingredients: {'Ham': '50g', 'Pineapple': '50g'},
  ),
  Product(
    id: 'pz3',
    name: 'Pepperoni Pizza',
    vendor: "Papa John's",
    price: 85,
    imageUrl: 'assets/images/pizza_pepperoni.png',
    colorHex: 'FFDAB9',
    description: 'Classic pepperoni pizza',
    ingredients: {'Pepperoni': '20 slices'},
  ),
  Product(
    id: 'pz4',
    name: 'Vegetarian Pizza',
    vendor: "Domino's",
    price: 95,
    imageUrl: 'assets/images/pizza_veg.png',
    colorHex: 'F0FFF0',
    description: 'Loaded with fresh veggies',
    ingredients: {'Veggies': 'Assorted'},
  ),
];
