import 'models/product.dart';

final List<Product> dummyProducts = [
  Product(
    id: 'p1',
    name: 'Strawberry Crack',
    vendor: "Dunkin's",
    price: 36,
    imageUrl: 'assets/images/strawberry_crack_donut_1772553367351.png',
    colorHex: 'FFF0F5',
    description: 'The Sweet And Subtle Salty Combo Of Chocolate Meets Caramel. Introduce The Caramel Duo To Your Mouth!',
    ingredients: {'Sugar': '8 Gram', 'Salt': '8 Gram', 'Fat': '12%', 'Energy': '140 Kcal'},
  ),
  Product(
    id: 'p2',
    name: 'Nuts Caramel',
    vendor: "Dunkin's",
    price: 45,
    imageUrl: 'assets/images/nuts_caramel_donut_1772553387131.png',
    colorHex: 'E0FFFF',
    description: 'Delicious nuts and caramel combined in an awesome donut.',
    ingredients: {'Sugar': '10 Gram', 'Salt': '2 Gram', 'Fat': '15%', 'Energy': '200 Kcal'},
  ),
  Product(
    id: 'p3',
    name: 'Red Velvet',
    vendor: "Dunkin's",
    price: 45,
    imageUrl: 'assets/images/red_velvet_donut_1772553406049.png',
    colorHex: 'FFE4E1',
    description: 'A classic red velvet experience in a donut.',
    ingredients: {'Sugar': '12 Gram', 'Salt': '1 Gram', 'Fat': '14%', 'Energy': '250 Kcal'},
  ),
  Product(
    id: 'p4',
    name: 'Strawberry',
    vendor: "Dunkin's",
    price: 84,
    imageUrl: 'assets/images/strawberry_donut_1772553452291.png',
    colorHex: 'FFF0F5',
    description: 'Classic strawberry glazed donut.',
    ingredients: {'Sugar': '9 Gram', 'Salt': '1 Gram', 'Fat': '10%', 'Energy': '150 Kcal'},
  ),
  Product(
    id: 'p5',
    name: 'Choco Tap',
    vendor: "Dunkin's",
    price: 95,
    imageUrl: 'assets/images/choco_tap_donut_1772553419712.png',
    colorHex: 'FFF8DC',
    description: 'Chocolate tapping goodness.',
    ingredients: {'Sugar': '14 Gram', 'Salt': '2 Gram', 'Fat': '16%', 'Energy': '280 Kcal'},
  ),
];
